apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: line-hr-bot-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/line-hr-bot-backend:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: LINE_CHANNEL_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: LINE_CHANNEL_ACCESS_TOKEN
        - name: LINE_CHANNEL_SECRET
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: LINE_CHANNEL_SECRET
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: GEMINI_API_KEY
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: SUPABASE_URL
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: SUPABASE_ANON_KEY
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_CHAT_ID
          valueFrom:
            secretKeyRef:
              name: line-bot-secrets
              key: TELEGRAM_CHAT_ID
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
          periodSeconds: 10