# Google Cloud Build configuration for automated deployment
steps:
  # Build backend image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args: [
      'build',
      '-f', 'Dockerfile.cloudrun',
      '-t', 'gcr.io/$PROJECT_ID/line-hr-bot-backend:latest',
      '.'
    ]
    
  # Build frontend image  
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'frontend'
    args: [
      'build', 
      '-f', 'Dockerfile.cloudrun',
      '-t', 'gcr.io/$PROJECT_ID/line-hr-bot-frontend:latest',
      '.'
    ]
    
  # Push backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/line-hr-bot-backend:latest'
    ]
    
  # Push frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/line-hr-bot-frontend:latest'
    ]
    
  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'line-hr-bot-backend',
      '--image', 'gcr.io/$PROJECT_ID/line-hr-bot-backend:latest',
      '--region', 'asia-southeast1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--concurrency', '80',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'PORT=8080,ENVIRONMENT=production',
      '--update-secrets', 
      'LINE_CHANNEL_ACCESS_TOKEN=LINE_CHANNEL_ACCESS_TOKEN:latest,LINE_CHANNEL_SECRET=LINE_CHANNEL_SECRET:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest,SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_KEY=SUPABASE_ANON_KEY:latest,TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,TELEGRAM_CHAT_ID=TELEGRAM_CHAT_ID:latest'
    ]
    
  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'line-hr-bot-frontend',
      '--image', 'gcr.io/$PROJECT_ID/line-hr-bot-frontend:latest',
      '--region', 'asia-southeast1', 
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '512Mi',
      '--cpu', '0.5',
      '--concurrency', '100',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'PORT=8080'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/line-hr-bot-backend:latest'
  - 'gcr.io/$PROJECT_ID/line-hr-bot-frontend:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# Timeout for the entire build
timeout: '1200s'

# Substitutions (removed unused _REGION variable)